server:
  port: 8004
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq

rabbitmq:
  exchange:
    name: message-exhange
  queue:
    name: message-queue
  routing:
    name: message-routing